version: '2'

services:
  persist:
    image: persist
    command: python main.py
    environment:
      - RECURRENT_REDIS_HOST=redis
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./media:/opt/persist/media
  persist_worker:
    build: .
    image: persist
    command: celery -A persist worker -l info --concurrency 6
    environment:
      - RECURRENT_REDIS_HOST=redis
    links:
      - redis
    depends_on:
      - redis
    volumes:
      - ./media:/opt/persist/media
  redis:
    image: redis
    ports:
      - "6379:6379"

